version: "3.9"
services:
  postgis:
    image: postgis/postgis
    container_name: postgis
    restart: always
    deploy:
        resources:
          limits:
            cpus: '1.00'
            memory: 1G
          reservations:
            cpus: '0.50'
            memory: 1G
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
        timeout: 45s
        interval: 10s
        retries: 10
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
